name: Deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'Deploy - v*.*.*'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Tags
        run: |
          echo "TAGS=${{ inputs.version }}"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

#      - name: Write application-version.yaml
#        run: |
#            echo "app:" > src/main/resources/application-version.yaml
#            echo "  version:" >> src/main/resources/application-version.yaml
#            echo "    ${{ inputs.version }}" >> src/main/resources/application-version.yaml

      - name: Cat application-version.yaml
        run: |
          echo "version: $(cat src/main/resources/application-version.yaml)"

      - name: Build with Gradle
        run: ./gradlew clean build -x test