name: CD
on:
  push:
    branches: ["main"]

jobs:
  extract-info:
    runs-on: ubuntu-latest
    outputs:
      module: ${{ steps.module_prefix.outputs.module }}
      tag: ${{ steps.tag_version.outputs.version }}
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Info
        run: |
          version=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          echo "version=$version" >> $GITHUB_OUTPUT
        id: extract_version

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}

  call-deploy:
    needs: extract-info
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      tags: ${{ needs.extract-info.outputs.tag }}
    permissions:
      contents: write